### ISSUE TITLE
Error in python library?

### ISSUE THREAD

**Issue by reddwarfff** [pimoroni/max30105-python#5]
Trying to use the sensor but when I try and run read-heartbeat.py, I gt the following error:
Traceback (most recent call last):
  File "/home/pi/max30105-python/examples/read-heartbeat.py", line 10, in <module>
    max30105.setup()
  File "/usr/local/lib/python3.5/dist-packages/max30105/__init__.py", line 319, in setup
    self.soft_reset(timeout=timeout)
  File "/usr/local/lib/python3.5/dist-packages/max30105/__init__.py", line 353, in soft_reset
    while self._max30105.get('MODE_CONFIG').reset and time.time() - t_start < timeout:
  File "/usr/local/lib/python3.5/dist-packages/i2cdevice/__init__.py", line 232, in get
    result[field] = self.get_field(register, field)
  File "/usr/local/lib/python3.5/dist-packages/i2cdevice/__init__.py", line 247, in get_field
    value = field.adapter._decode(value)
  File "/usr/local/lib/python3.5/dist-packages/i2cdevice/adapter.py", line 26, in _decode
    raise ValueError("{} not in lookup table".format(value))
ValueError: 0 not in lookup table

Please help!

**Comment by reddwarfff** [comment]
Thanks Phil, I tried that but no joy I’m afraid. If you manage to fix it could you let me know? Many thanks, Sarah

**Comment by Gadgetoid** [comment]
It looks like it's reset back to 0 when the library initialises and resets the sensor. In retrospect that makes sense, but I don't know why it's suddenly become an issue. I had the same problem with a new sensor I pulled from stock, but my old test sensor has grown legs and walked off so I've no basis for comparison yet.

Either way, the fix is simple enough that I'm happy to roll it out, and I'll worry about the why elsewhere.

**Comment by Gadgetoid** [comment]
Should be fixed as of v0.0.3 - https://github.com/pimoroni/max30105-python/releases/tag/v0.0.3

**Comment by reddwarfff** [comment]
Thank you! Will try again as soon as home!
